# Generated by Django 4.2.5 on 2023-09-20 11:43

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_category_id_alter_currency_id_alter_state_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('4e4de164-a50d-4cd8-839e-57edcb8a0f18'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('state', models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            options={
                'abstract': False,
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('synced', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('4e4de164-a50d-4cd8-839e-57edcb8a0f18'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('status_code', models.CharField(default='000.000.000', max_length=10)),
                ('trace', models.FilePathField(allow_folders=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_client_viewable', models.BooleanField(default=False)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.actiontype')),
                ('state', models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Action_By', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Actions',
                'unique_together': {('action_type', 'reference')},
            },
        ),
    ]
