# Generated by Django 4.2.5 on 2023-09-20 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d652e12d-1f09-4c0f-b83b-03136d5b02d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d652e12d-1f09-4c0f-b83b-03136d5b02d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
