# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_action_id_alter_actiontype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24f7b07-269e-49f2-b7e6-71e15f82cebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24f7b07-269e-49f2-b7e6-71e15f82cebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
