# .travis.yml

language: python
python:
  - "3.8"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydatabase;" -U postgres

script:
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls
