# Generated by Django 4.2.5 on 2023-09-20 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_id_alter_currency_id_alter_state_id'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9626c060-e965-4f66-b76b-041902df5f20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(default=uuid.UUID('f1c6100d-64b2-48cd-be83-deb21e1c26c6'), on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
