# Generated by Django 4.2.5 on 2023-09-20 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0650ad2f-936e-708b-8000-6505bd46dce3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0650ad2f-936e-708b-8000-6505bd46dce3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
