# Generated by Django 4.2.5 on 2023-09-20 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e4de164-a50d-4cd8-839e-57edcb8a0f18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e4de164-a50d-4cd8-839e-57edcb8a0f18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e4de164-a50d-4cd8-839e-57edcb8a0f18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
