# Generated by Django 4.2.5 on 2023-09-17 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06506dea-9b2b-7181-8000-dbf5ee38a570'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06506dea-9b2b-7181-8000-dbf5ee38a570'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06506dea-9b2b-7181-8000-dbf5ee38a570'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
