# Generated by Django 4.2.5 on 2023-09-20 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_id_alter_currency_id_alter_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0650ad2f-936e-708b-8000-6505bd46dce3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0650ad2f-936e-708b-8000-6505bd46dce3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0650ad2f-936e-708b-8000-6505bd46dce3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
