# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_id_alter_currency_id_alter_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24f7b07-269e-49f2-b7e6-71e15f82cebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24f7b07-269e-49f2-b7e6-71e15f82cebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24f7b07-269e-49f2-b7e6-71e15f82cebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
