# Generated by Django 4.2.5 on 2023-09-17 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06506deb-ecf6-7790-8000-335458c48cbc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
